// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveRule(arg1) {
  return window['go']['app']['App']['ArchiveRule'](arg1);
}

export function Ask(arg1) {
  return window['go']['app']['App']['Ask'](arg1);
}

export function Cancel() {
  return window['go']['app']['App']['Cancel']();
}

export function ContextStat() {
  return window['go']['app']['App']['ContextStat']();
}

export function CreatePersona(arg1, arg2) {
  return window['go']['app']['App']['CreatePersona'](arg1, arg2);
}

export function DeleteMemory(arg1) {
  return window['go']['app']['App']['DeleteMemory'](arg1);
}

export function DeletePersona(arg1) {
  return window['go']['app']['App']['DeletePersona'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['app']['App']['DeleteRule'](arg1);
}

export function DeleteRuleCandidate(arg1) {
  return window['go']['app']['App']['DeleteRuleCandidate'](arg1);
}

export function ExportPersonaToFile(arg1) {
  return window['go']['app']['App']['ExportPersonaToFile'](arg1);
}

export function GetPersonaChanges(arg1) {
  return window['go']['app']['App']['GetPersonaChanges'](arg1);
}

export function GetPersonaMeta() {
  return window['go']['app']['App']['GetPersonaMeta']();
}

export function GetPersonaRules(arg1) {
  return window['go']['app']['App']['GetPersonaRules'](arg1);
}

export function GetPersonaSnapshot() {
  return window['go']['app']['App']['GetPersonaSnapshot']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function History() {
  return window['go']['app']['App']['History']();
}

export function ImportPersonaFromFile() {
  return window['go']['app']['App']['ImportPersonaFromFile']();
}

export function Memories() {
  return window['go']['app']['App']['Memories']();
}

export function PromoteRuleCandidate(arg1) {
  return window['go']['app']['App']['PromoteRuleCandidate'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RenamePersona(arg1, arg2) {
  return window['go']['app']['App']['RenamePersona'](arg1, arg2);
}

export function ReviveRule(arg1) {
  return window['go']['app']['App']['ReviveRule'](arg1);
}

export function RuleCandidates(arg1) {
  return window['go']['app']['App']['RuleCandidates'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['app']['App']['SaveRule'](arg1);
}

export function SaveSeedText(arg1, arg2) {
  return window['go']['app']['App']['SaveSeedText'](arg1, arg2);
}

export function Say(arg1) {
  return window['go']['app']['App']['Say'](arg1);
}

export function SessionMessages(arg1) {
  return window['go']['app']['App']['SessionMessages'](arg1);
}

export function SetActivePersona(arg1) {
  return window['go']['app']['App']['SetActivePersona'](arg1);
}

export function SetMenuOpen(arg1) {
  return window['go']['app']['App']['SetMenuOpen'](arg1);
}

export function SetRuleEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetRuleEnabled'](arg1, arg2);
}

export function SetThinkingDisabled(arg1) {
  return window['go']['app']['App']['SetThinkingDisabled'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['app']['App']['ToggleWindow']();
}
