// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {persona} from '../models';
import {app} from '../models';

export function ApproveDowngrade(arg1:string):Promise<void>;

export function ArchiveRule(arg1:string):Promise<void>;

export function Ask(arg1:string):Promise<string>;

export function Cancel():Promise<void>;

export function ContextStat():Promise<ui.ContextStat>;

export function CreatePersona(arg1:string,arg2:string):Promise<string>;

export function DeleteMemory(arg1:string):Promise<void>;

export function DeletePersona(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteRuleCandidate(arg1:string):Promise<void>;

export function ExportPersonaToFile(arg1:string):Promise<string>;

export function GetPersonaChanges(arg1:string):Promise<Array<persona.PersonaChange>>;

export function GetPersonaMeta():Promise<persona.Meta>;

export function GetPersonaRules(arg1:string):Promise<Array<persona.PersonaRule>>;

export function GetPersonaSnapshot():Promise<persona.Snapshot>;

export function GetSettings():Promise<app.AppSettings>;

export function HideWindow():Promise<void>;

export function History():Promise<Array<ui.HistorySession>>;

export function ImportPersonaFromFile():Promise<persona.Persona>;

export function Memories():Promise<Array<ui.MemoryItem>>;

export function PendingDowngrade():Promise<persona.PersonaRule>;

export function PromoteRuleCandidate(arg1:persona.Candidate):Promise<void>;

export function Quit():Promise<void>;

export function RefuseDowngrade(arg1:string):Promise<void>;

export function RenamePersona(arg1:string,arg2:string):Promise<void>;

export function ReviveRule(arg1:string):Promise<void>;

export function RuleCandidates(arg1:string):Promise<Array<persona.Candidate>>;

export function SaveRule(arg1:persona.PersonaRule):Promise<string>;

export function SaveSeedText(arg1:string,arg2:string):Promise<void>;

export function Say(arg1:string):Promise<void>;

export function SessionMessages(arg1:string):Promise<Array<ui.HistoryItem>>;

export function SetActivePersona(arg1:string):Promise<void>;

export function SetMenuOpen(arg1:boolean):Promise<void>;

export function SetRuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetSearchDisabled(arg1:boolean):Promise<void>;

export function SetSearchURL(arg1:string):Promise<void>;

export function SetThinkingDisabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
