// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function Ask(arg1:string):Promise<string>;

export function Cancel():Promise<void>;

export function HideWindow():Promise<void>;

export function History():Promise<Array<ui.HistoryItem>>;

export function Quit():Promise<void>;

export function Say(arg1:string):Promise<void>;

export function SetMenuOpen(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
