// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1:string):Promise<string>;

export function Cancel():Promise<void>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function Say(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
