// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {persona} from '../models';
import {main} from '../models';
import {ui} from '../models';

export function Ask(arg1:string):Promise<string>;

export function Cancel():Promise<void>;

export function CreatePersona(arg1:string,arg2:string):Promise<string>;

export function DeletePersona(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function ExportPersonaToFile(arg1:string):Promise<string>;

export function GetPersonaChanges(arg1:string):Promise<Array<persona.PersonaChange>>;

export function GetPersonaMeta():Promise<persona.Meta>;

export function GetPersonaRules(arg1:string):Promise<Array<persona.PersonaRule>>;

export function GetPersonaSnapshot():Promise<persona.Snapshot>;

export function GetSettings():Promise<main.AppSettings>;

export function HideWindow():Promise<void>;

export function History():Promise<Array<ui.HistoryItem>>;

export function ImportPersonaFromFile():Promise<persona.Persona>;

export function Quit():Promise<void>;

export function RenamePersona(arg1:string,arg2:string):Promise<void>;

export function SaveRule(arg1:persona.PersonaRule):Promise<string>;

export function SaveSeedText(arg1:string,arg2:string):Promise<void>;

export function Say(arg1:string):Promise<void>;

export function SetActivePersona(arg1:string):Promise<void>;

export function SetMenuOpen(arg1:boolean):Promise<void>;

export function SetRuleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetThinkingDisabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
