// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Say(arg1) {
  return window['go']['main']['App']['Say'](arg1);
}

export function SetMenuOpen(arg1) {
  return window['go']['main']['App']['SetMenuOpen'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
